version: "3.8"

services:
  server:
    image:  'nginx:stable-alpine'
    container_name: mvc-nginx
    ports:
     - '80:80'
    volumes :
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  php:
    container_name: mvc-php
    build:
      context: ./docker/dockerfiles
      dockerfile: php.dockerfile
    volumes:
     - ./:/var/www/html

  mysql:
   container_name: mvc-mysql
   platform: linux/x86_64 
   image: mysql:8
   ports:
      - "3307:3306"
   env_file:
    - ./docker/env/mysql.env

